controllers/SiteController.php
<?php

namespace app\controllers;

use DateTime;
use Yii;
use yii\web\UploadedFile;
use yii2mod\rbac\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\SmartIdForm;
use app\models\User;
use app\models\Callbacks;
use app\models\TemplateForm;
use app\components\Helpers;
use yii\helpers\Json;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\db\Expression;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'smart-id', 'signup', 'test-clave-unica', 'test-callback-clave-unica'],
                'rules' => [

                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['smart-id'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['template'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['test-clave-unica', 'test-callback-clave-unica'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['POST'],
                    'callback' => ['POST'],
                    'user-info' => ['POST'],
                    'test-clave-unica' => ['GET'],
                    'test-callback-clave-unica' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'login' => [
                'class' => 'yii2mod\user\actions\LoginAction'
            ],
            'logout' => [
                'class' => 'yii2mod\user\actions\LogoutAction'
            ],
            'signup' => [
                'class' => 'yii2mod\user\actions\SignupAction',
                'on afterSignup' => function ($event) {
                    $master_user = User::findOne(Yii::$app->user->id);
                    $signup_user = $event->getForm()->getUser();
                    $slave_user = User::findOne($signup_user->id);
                    $slave_user->api_key_toc = $master_user->api_key_toc;
                    $slave_user->template_id = $master_user->template_id;
                    $slave_user->save(false);
                },
            ],
            'request-password-reset' => [
                'class' => 'yii2mod\user\actions\RequestPasswordResetAction'
            ],
            'password-reset' => [
                'class' => 'yii2mod\user\actions\PasswordResetAction'
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionTemplate()
    {
        $user = User::findOne(\Yii::$app->user->id);
        if (!$user || $user->api_key_toc == "") {
            throw new HttpException(207, 'Usuario no posee Api key para utilizar el servicio.');
        }
        $token = $user->api_key_toc;
        $model = new TemplateForm();
        $model->color_background = "#ffffff";
        $model->color_font = "#00000";
        $model->color_font_primary = "#ffffff";
        $model->color_font_secondary = "#ffffff";
        $model->color_primary = "#2f2fd0";
        $model->color_secondary = "#2626a1";
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $image = UploadedFile::getInstance($model, 'image');
                if (!is_null($image)) {
                    $img_path = $image->tempName;
                    $img_data = file_get_contents($img_path);
                    $model->logo = base64_encode($img_data);
                }
                $headers = [];
                $headers2 = [];
                $headers['Authorization'] = 'Bearer ' . $token;
                $headers['Content-Type'] = 'application/json';
                foreach ($headers as $k => $v) {
                    $headers2[] = $k . ': ' . $v;
                }
                $payload = Json::encode($model->attributes);
                try {
                    Yii::info($headers2);
                    Yii::info($payload);
                    $response = Helpers::curl_get_contents(Yii::$app->params['endpoint_template'], $headers2, 'POST', $payload);
                    Yii::info($response);
                    if (isset($response->data)) {
                        $user = User::findOne(Yii::$app->user->id);
                        $user->template_id = $response->data->id;
                        $user->save(false);
                    }
                } catch (yii\base\Exception $e) {
                    $response = $e->getTraceAsString();
                }
                Yii::info($payload);
                Yii::$app->session->setFlash('templateFormSubmitted');
            }
        }

        return $this->render('template', [
            'model' => $model,
        ]);
    }


    /**
     * Displays SmartId.
     *
     * @return string
     */
    public function actionSmartId()
    {
        $user = User::findOne(\Yii::$app->user->id);
        if (!$user || $user->api_key_toc == "") {
            throw new HttpException(207, 'Usuario no posee Api key para utilizar el servicio.');
        }
        $token = $user->api_key_toc;
        $template = $user->template_id;
        $model = new SmartIdForm();
        $model->name = true;
        $model->last_name = true;
        $model->full_name = true;
        $model->rut = true;
        $model->serial_number = true;
        $model->ci_expiration = true;
        $model->age = true;
        $model->gender = true;
        $model->callback_url = Url::to(['site/callback'], true);
        $qr_image = null;
        $qr_url = null;
        $response = null;
        if ($model->load(Yii::$app->request->post())) {
            $headers = [];
            $headers2 = [];
            $headers['Authorization'] = 'Bearer ' . $token;
            $headers['Content-Type'] = 'application/json';
            foreach ($headers as $k => $v) {
                $headers2[] = $k . ': ' . $v;
            }
            $filters = [];
            foreach ($model->attributes as $attribute => $value) {
                if ($value == 1 || $value == '1') {
                    $filters[$attribute] = true;
                }
            }
            $payload = Json::encode([
                'callbackUrl' => $model->callback_url,
                'filters' => $filters,
                'cID' => $user->id,
                'frontCustomizationId' => $template,
                'verificationType' => 'liveness',
                'urlRedirect' => Url::to(['site/exito'], true),
            ]);
            try {
                Yii::info($headers2);
                Yii::info($payload);
                $response = Helpers::curl_get_contents(Yii::$app->params['endpoint'], $headers2, 'POST', $payload);
                Yii::info($response);
                if (isset($response->data)) {
                    if (isset($response->data->qr_code)) {
                        $qr_image = $response->data->qr_code;
                        $qr_url = $response->data->qr_content;
                    }
                }
            } catch (yii\base\Exception $e) {
                $response = $e->getTraceAsString();
            }

            Yii::$app->session->setFlash('smartIdFormSubmitted');
        }
        return $this->render('smart_id', ['model' => $model, 'qr_image' => $qr_image, 'qr_url' => $qr_url, 'response' => $response]);
    }


    public function actionCallback()
    {
        if (Yii::$app->request->isPost) {
            $data = Yii::$app->request->post();
            Yii::info($data);
            $callback = new Callbacks();
            $callback->toc = Json::encode($data['toc']);
            $callback->cID = $data['cID'];
            $callback->token = $data['token'];
            $callback->save(false);
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            return [
                'status' => 200,
            ];
        }
    }


    public function actionUserInfo()
    {
        if (Yii::$app->request->isPost) {
            $data = Yii::$app->request->post();
            Yii::info($data);
            $expression = new Expression("DATE_SUB(NOW(), INTERVAL 5 SECOND)");
            $callback = Callbacks::find()->where(['cID' => $data['cID']])->andWhere(['>=', 'created_at', $expression])->one();
            if ($callback) {
                $html = "";
                $data_callback = Json::decode($callback->toc);
                foreach ($data_callback as $key => $value) {
                    $html .= $key . ": " . $value . "\n";
                }
                $html .= 'TOC TOKEN: ' . $callback->token;
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return [
                    'status' => 200,
                    'html' => $html
                ];
            }

        }
    }

    /**

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/exito.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Exito!';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        Se ha realizado con exito la validacion de datos, puedes volver al sitio
    </p>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Smart Id 7OC';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>¡Bienvenido a Identidad Digital!</h1>

        <p class="lead">Realizaras el enrolamiento desde la generacion de un codigo Qr en unos simples pasos.</p>

<!--         <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
 -->    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Paso 1</h2>

                <p>Genera tu codigo QR o copia el enlace generado</p>
                <div class="text-center">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3ier2nnSh7yFF8xUSXjueG9oVq4vV58z46Q&usqp=CAU"></img>
                </div>
            </div>
            <div class="col-lg-4">
                <h2>Paso 2</h2>

                <p>Escanea el codigo QR que aparece a continuación o dirigete a la URL previamente copiada</p>
                <div >
                <img width="320px" src="https://image.freepik.com/vector-gratis/smartphone-su-concepto-mano-escanear-codigo-qr_147754-197.jpg"></img>
                </div>
            </div>
            <div class="col-lg-4">
                <h2>Paso 3</h2>

                <p>¡Realiza el enrolamiento!</p>
                <div class="text-center">
                <img width="350px" src="https://image.freepik.com/vector-gratis/smartphone-mujer-reconocimiento-escaneo-biometrico_24908-56395.jpg"></img>
                </div>
            </div>
        </div>
        <br/>
        <div class="text-center">
        <p><a class="btn btn-lg btn-success" href="/site/smart-id">Ir a Smart ID</a></p>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/smart_id.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\SmartIdForm */
/* @var $qr_image string */
/* @var $qr_url string */
/* @var $response string|Array */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$url = Url::to(['site/user-info'], true);
$user_id = Yii::$app->user->identity->id;
$script = <<<JS
var interval = null;
$(document).ready(function() {
    interval = setInterval(function() {
        getUserInfo();
    }, 5000);

});
function getUserInfo() {
    $.ajax({
        type: "POST",
        url: "{$url}",
        data: {
            "cID": "{$user_id}"
        },
        success: function(response) {
            if (response.status == 200) {
                swal("Información obtenida correctamente", response.html, "success");
            }
        },
        err: function(err) {}
    });
};
JS;

$this->registerJs($script);

$this->title = 'Generador de QR';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-index">

    <div class="body-content">

        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-6">

                        <h2>SmartId 7OC</h2>
                        <p>Seleccione las opciones que desea extraer y presione generar para crear un codigo QR que te guiara en el proceso.</p>
                        <br/>

                        <?php $form = ActiveForm::begin(['id' => 'smart-id-form']); ?>
                        <?= $form->field($model, 'name')->checkbox(['readonly' => (!Yii::$app->user->isGuest && Yii::$app->user->id != '100') ? true : false]) ?>
                        <?= $form->field($model, 'last_name')->checkbox(['readonly' => (!Yii::$app->user->isGuest && Yii::$app->user->id != '100') ? true : false]) ?>
                        <?= $form->field($model, 'full_name')->checkbox(['readonly' => (!Yii::$app->user->isGuest && Yii::$app->user->id != '100') ? true : false]) ?>
                        <?= $form->field($model, 'rut')->checkbox(['readonly' => (!Yii::$app->user->isGuest && Yii::$app->user->id != '100') ? true : false]) ?>
                        <?= $form->field($model, 'serial_number')->checkbox(['readonly' => (!Yii::$app->user->isGuest && Yii::$app->user->id != '100') ? true : false]) ?>
                        <?= $form->field($model, 'ci_expiration')->checkbox(['readonly' => (!Yii::$app->user->isGuest && Yii::$app->user->id != '100') ? true : false]) ?>
                        <?= $form->field($model, 'age')->checkbox(['readonly' => (!Yii::$app->user->isGuest && Yii::$app->user->id != '100') ? true : false]) ?>
                        <?= $form->field($model, 'gender')->checkbox(['readonly' => (!Yii::$app->user->isGuest && Yii::$app->user->id != '100') ? true : false]) ?>
                        <?= $form->field($model, 'callback_url')->textInput(['disabled' => (!Yii::$app->user->can('superadmin')) ? true : false]) ?>

                        <div class="form-group text-center">
                            <?= Html::submitButton('Generar Codigo QR', ['class' => 'btn btn-success btn-lg ', 'name' => 'smart-id-button']) ?>
                        </div>

                        <?php ActiveForm::end(); ?>
                    </div>
                    <div class="col-lg-6 text-center" >
                        <?php if (Yii::$app->session->hasFlash('smartIdFormSubmitted')) : ?>
                            <?php if($qr_image != null): ?>
                                <div class="alert alert-success">
                                    Gracias por utilizar el generador, el codigo esta mas abajo.
                                </div>
                                <p>Haz click en el boton <i class="glyphicon glyphicon-copy"></i> para copiar el link</span></p>
                                <div class="input-group">
                                    <?= Html::input('text','qr-url-input',$qr_url,['id'=>'input','readonly'=>true,'class'=>'form-control']) ?>
                                    <span class="input-group-btn">
                                        <?= Html::button('<i class="glyphicon glyphicon-copy"></i>',['onclick'=>'myFunction()','class'=>'btn btn-primary']) ?>
                                    </span>
                                </div>
                                <p><?= Html::img('data:image/png;base64,' . $qr_image);?></p>
                            <?php
                                $url="data:image/png;base64," . $qr_image;
                                $date = date("Y-m-d_H:i:s");
                                echo Html::a('Descargar Qr', $url, ['download'=>'qr_'.$date.'.jpg', 'class'=> 'btn btn-primary btn-lg btn-block' ]);
                            else: ?>
                                <div class="alert alert-danger">
                                    Ha ocurrido un error al obtener el codigo QR, Recuerda que debes seleccionar al menos una de las opciones del formulario, intenta nuevamente y si aun persiste el problema comunicate con TI.
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/template.php
<?php

use kartik\color\ColorInput;
use kartik\file\FileInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TemplateForm */
/* @var $form ActiveForm */

$this->title = 'Personalizacion de Interfaz';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-template">
    <div class="body-content">

        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <?php if (Yii::$app->session->hasFlash('templateFormSubmitted')) : ?>
                        <div class="alert alert-success">
                            Se han guardado tus configuraciones de apariencia.
                        </div>
                    <?php endif; ?>
                    <div class="col-lg-6">

                        <h2>Apariencia</h2>
                        <p>Seleccione los colores e imagen que se asociara a sus requerimientos de Smart Id.</p>
                        <br/>

                        <?php $form = ActiveForm::begin(); ?>

                        <?= $form->field($model, 'image')->widget(FileInput::classname(), [
                            'options' => ['accept' => 'image/*'],
                            'pluginOptions'=>['allowedFileExtensions'=>['jpg','gif','png'],'showUpload' => false,],
                        ]);   ?>
                        <?= $form->field($model, 'color_background')->widget(ColorInput::classname(), [
                            'options' => ['placeholder' => 'Seleccione color ...'],
                        ]) ?>
                        <?= $form->field($model, 'color_font')->widget(ColorInput::classname(), [
                            'options' => ['placeholder' => 'Seleccione color ...'],
                        ]) ?>
                        <?= $form->field($model, 'color_primary')->widget(ColorInput::classname(), [
                            'options' => ['placeholder' => 'Seleccione color ...'],
                        ]) ?>
                        <?= $form->field($model, 'color_font_primary')->widget(ColorInput::classname(), [
                            'options' => ['placeholder' => 'Seleccione color ...'],
                        ]) ?>
                        <?= $form->field($model, 'color_secondary')->widget(ColorInput::classname(), [
                            'options' => ['placeholder' => 'Seleccione color ...'],
                        ]) ?>
                        <?= $form->field($model, 'color_font_secondary')->widget(ColorInput::classname(), [
                            'options' => ['placeholder' => 'Seleccione color ...'],
                        ]) ?>

                        <div class="form-group">
                            <?= Html::submitButton('Aplicar', ['class' => 'btn btn-primary']) ?>
                        </div>
                        <?php ActiveForm::end(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div><!-- site-template -->